theme: jekyll-theme-hacker
title: Arushi's APCSA final project 
description: This website is for my APCSA final project

Brag sheet:

National Honor Society
President Volunteer Service Award (Bronze and Silver)
National Merit Scholarship (99th Percentile)

Experience:

Hour of Code Leader— East Brunswick, NJ-- December 2020 to Present
- Managed project execution and led the team to ensure adherence to budget, schedule, and scope for the annual Hour of Code event.
- Managed social media accounts and marketing across different platforms. 
- Assign duties and responsibilities to personnel, monitor project milestones and deliverables.
- Ran HTML and cybersecurity workshops

Voluntary Tutor — East Brunswick, NJ-- September 2020 to Present
- Tutor students in all subjects (Chemistry, Physics, Precalculus, English etc.) and preparing them for the American Mathematics Contest 8 (AMC  8)

East Brunswick FIRST Programmer— East Brunswick, NJ-- June 2020 to Present
- Programmer for the Robotics Team, program our robot for the FIRST Robotics Competition 2021 and took part in the Game Design Challenge 

Future Business Leaders of America (FBLA) — East Brunswick, NJ-- September 2019 to Present
- Led meetings, prepare for careers in business through academic competitions (FBLA Competitive Events), leadership development, and educational programs

Youth Council Volunteer — East Brunswick, NJ-- September 2018 to Present
- Accumulated over 200 hours volunteering for a non-profit organization where I lead other young volunteers and work with kids with learning disabilities

East Brunswick Girls Basketball - September 2018 to Present


Technical Skills
Microsoft Office, Java, JavaScript, Python, HTML  

Soft Skills    
Communication and Presentation, Leadership, Teamwork 

# social links
instagram_username: arushipradhan_
email: arushi18p@gmail.com
github_username:  arushi18p




