theme: jekyll-theme-cayman
title: arushi's APCSP final project 
description: this is a website about me 

# social links
instagram_username: arushipradhan_
email: arushi18p@gmail.com
github_username:  arushi18p



show_excerpts: false
