theme: jekyll-theme-cayman
title: Arushi's APCSP final project 
description: This website is for my APCSP final project

# social links
instagram_username: arushipradhan_
email: arushi18p@gmail.com
github_username:  arushi18p




